sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioos:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tJfK4vwMpcJLnSJN5Qp
    access-key-secret: hYeEIyko0TEmwXzfNC6s12uhH5sZOL
    bucket-name: maoxian-sky-take-out